# Site settings
title: "Landryshuai"
description: "天地不仁，以万物为刍狗。"
keywords: "jekyll, template, landryshuai"
baseurl: ""
url: "http:////landryshuai.github.io"
highlighter: pygments
paginate: 5
author:
    name: landryshuai
    github: landryshuai
    email: landry.sjm@gmail.com
    gitcafe: landryshuai
    twitter:
    facebook:
    googleplus:
    weibo: landryshuai
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:categories/:year-:month/:title.html

# comment
comments:
    duoshuo:
        name:                               # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid:                             # 百度统计 js 代码后的字符串

# blogroll
blogroll: true
brlist:
    - text: "Havee's Space"
      url : //havee.me/
    - text: "小气的神"
      url : //www.mdong.org/
    - text: "冰河"
      url : //tianchunbinghe.blog.163.com/
